#!/bin/bash
LIGEROPACKAGES=(
core/AccountedTime-6.0.7.opm
core/APIAdmin-6.0.1.opm
core/ArticleEdit-6.0.2.opm
core/ArticleListAndTimeCalculation-6.0.1.opm
core/AutoTicket-6.0.3.opm
core/Dashboards-6.0.5.opm
core/DynamicFieldTextMask-6.0.4.opm
core/DynamicSurvey-6.0.1.opm
core/DynamicView-6.0.2.opm
core/EasyNewService-6.0.0.opm
core/FAQ-6.0.28.opm
core/Followers-6.0.0.opm
core/Forms-6.0.22.opm
core/GeneralCatalog-6.0.30.opm
core/HighCharts-6.0.1.opm
core/ImportExport-6.0.30.opm
core/ITSMChangeManagement-6.0.30.opm
core/ITSMConfigurationManagement-6.0.30.opm
core/ITSMCore-6.0.30.opm
core/ITSMIncidentProblemManagement-6.0.30.opm
core/ITSMServiceLevelManagement-6.0.30.opm
core/Kanboard-6.0.4.opm
core/LigeroAPI-6.1.7.opm
core/LigeroDfAttachment-6.0.7.opm
core/LigeroEasyConnector-6.1.4.opm
core/LigeroEnterprise-6.0.3.opm
core/LigeroFix-6.0.8.opm
core/LigeroPortal-6.1.4.opm
core/LigeroSkins-6.0.9.opm
core/LigeroSmart-6.1.8.opm
core/LigeroToro-6.0.5.opm
core/MarkJS-6.0.1.opm
core/MaximizePopup-6.0.1.opm
core/MultilanguageServiceCatalog-6.0.1.opm
core/OLA-6.0.8.opm
core/RocketChat-6.0.5.opm
core/ServiceCatalogSidebarFaqAlerts-6.0.2.opm
core/ServiceCatalogSidebarFixNow-6.0.3.opm
core/ServiceCatalogSidebarOpenTickets-6.0.2.opm
core/ServiceCatalogSidebarServiceStatus-6.0.3.opm
core/ServiceCatalogSidebarTopService-6.0.4.opm
core/ServiceDynamicField-6.0.1.opm
core/ServiceTicketQueue-6.0.2.opm
core/ServiceTicketType-6.0.1.opm
core/SlaStop-6.0.1.opm
core/SmartClassification-6.0.1.opm
core/SmsNotify-6.0.0.opm
core/Survey-6.0.19.opm
core/ToolBarCiSearch-6.0.0.opm
core/TrackSolutionTime-6.0.12.opm
core/UpdateParentProcessValidation-6.0.2.opm
)

for package in "${LIGEROPACKAGES[@]}"
do
    wget -P /app-backups/ https://addons.ligerosmart.org/6.0/$package
done